<?php

namespace StoreBundles;

use StoreBundles\Store_bundles_ext;
use PHPUnit_Framework_TestCase;

require('../ext.store_bundles.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-07 at 10:11:48.
 */
class Store_bundles_extTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Store_bundles_ext
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Store_bundles_ext;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Store_bundles_ext::settings
     * @todo   Implement testSettings().
     */
    public function testSettings()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Store_bundles_ext::activate_extension
     * @todo   Implement testActivate_extension().
     */
    public function testActivate_extension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Store_bundles_ext::store_order_recalculate_end
     * @todo   Implement testStore_order_recalculate_end().
     */
    public function testStore_order_recalculate_end()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Store_bundles_ext::get_bundle_entries
     * @todo   Implement testGet_bundle_entries().
     */
    public function testGet_bundle_entries()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Store_bundles_ext::get_cart_items
     * @todo   Implement testGet_cart_items().
     */
    public function testGet_cart_items()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Store_bundles_ext::get_item_ids
     * @todo   Implement testGet_item_ids().
     */
    public function testGet_item_ids()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Store_bundles_ext::get_multi_ids
     * @todo   Implement testGet_multi_ids().
     */
    public function testGet_multi_ids()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Store_bundles_ext::detect_multi_discount
     * @todo   Implement testDetect_multi_discount().
     */
    public function testDetect_multi_discount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Store_bundles_ext::disable_extension
     * @todo   Implement testDisable_extension().
     */
    public function testDisable_extension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Store_bundles_ext::update_extension
     * @todo   Implement testUpdate_extension().
     */
    public function testUpdate_extension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
